import { storage } from "../storage";
import { deriveImagePromptId } from "../id-generator";
import { generateJson, now } from "../story/base";
import { StoryScript } from "../story/script";
import { StoryCharacter } from "../story/character";
import { StoryScene, StorySceneFile } from "../story/scene";

export interface ImagePrompt {
  id: string;
  sceneId: string;
  sceneNumber: number;
  purpose: string;
  prompt: string;         // scene-specific content only
  baseStyle: string;      // shared style block appended in code — same for all scenes
  negativePrompt: string;
  fullPrompt: string;     // prompt + baseStyle — ready to send to image model
  createdAt: string;
}

export interface ImagePromptFile {
  id: string;
  scriptId: string;
  title: string;
  baseStyle: string;      // stored once here, not repeated inside each prompt
  prompts: ImagePrompt[];
  createdAt: string;
}

const NEGATIVE_PROMPT =
  "blurry, low quality, distorted face, deformed hands, cartoon, anime, " +
  "watermark, text, logo, oversaturated, duplicate, bad anatomy";

/**
 * Build the shared style block from script-level fields.
 * This is appended in code to every scene prompt — never generated by AI.
 */
function buildBaseStyle(script: StoryScript): string {
  return [
    script.visualStyle,
    script.colorMood,
    script.weather,
    script.timePeriod,
    "photorealistic",
    "highly detailed",
    "cinematic lighting",
    "vertical composition",
    "9:16 aspect ratio",
  ]
    .filter(Boolean)
    .join(", ");
}

/**
 * AI only generates the scene-specific content:
 * who is in the scene, what they are doing, the focal moment.
 * Style and quality tags are handled by buildBaseStyle.
 */
function buildAiPrompt(
  scenes: StoryScene[],
  characters: StoryCharacter[],
  script: StoryScript,
): string {
  const characterList = characters
    .map((c) => `- ${c.name} (${c.gender}, ${c.age}): ${c.appearance}, ${c.clothing}`)
    .join("\n");

  const sceneList = scenes
    .map((s) => `Scene ${s.sceneNumber} (${s.purpose}): ${s.description} | emotion: ${s.emotion}`)
    .join("\n");

  return `
You are an AI image prompt engineer for short-form video content.

Write one scene-specific image prompt per scene.

Rules:
- Focus on ONE clear focal moment per scene — the single most important visual element
- Do NOT try to show multiple characters, objects, or actions at once
- Use the character's exact name, appearance, and clothing as described
- Describe what is physically visible: who, where, what they are doing
- Write as a comma-separated string — no full sentences
- Do NOT include style, lighting, mood, or quality tags — those are added separately
- Keep each prompt under 80 words

Setting: ${script.location}

Characters:
${characterList}

Scenes:
${sceneList}

Return ONLY valid JSON — an array of exactly ${scenes.length} objects:
[
  {
    "sceneNumber": 1,
    "prompt": "scene-specific content only, no style tags"
  }
]
`.trim();
}

export class ImagePromptGenerator {
  async generate(
    sceneFile: StorySceneFile,
    characters: StoryCharacter[],
    script: StoryScript,
  ): Promise<ImagePromptFile> {
    console.log(`🖼  Generating image prompts for: ${script.title}`);

    const baseStyle = buildBaseStyle(script);

    const parsed = await generateJson<Array<{
      sceneNumber: number;
      prompt: string;
    }>>(buildAiPrompt(sceneFile.scenes, characters, script));

    const timestamp = now();

    const prompts: ImagePrompt[] = parsed.map((raw) => {
      const scene = sceneFile.scenes.find((s) => s.sceneNumber === raw.sceneNumber)!;
      const prompt = raw.prompt.trim();
      return {
        id: deriveImagePromptId(scene.id),
        sceneId: scene.id,
        sceneNumber: raw.sceneNumber,
        purpose: scene.purpose,
        prompt,
        baseStyle,
        negativePrompt: NEGATIVE_PROMPT,
        fullPrompt: `${prompt}, ${baseStyle}`,
        createdAt: timestamp,
      };
    });

    const fileId = `PROMPT-${sceneFile.id.split("-").slice(1).join("-")}`;

    const promptFile: ImagePromptFile = {
      id: fileId,
      scriptId: script.id,
      title: script.title,
      baseStyle,
      prompts,
      createdAt: timestamp,
    };

    await storage.save("media/image-prompts", promptFile.id, promptFile);
    return promptFile;
  }
}
